# Victor AI - Personal AI Companion for Android
# Copyright (C) 2025-2026 Olga Kalinina

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.

"""Initial migration

Revision ID: 1e291a82539e
Revises: 
Create Date: 2026-01-07 08:21:21.252487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e291a82539e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_meta',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=True),
    sa.Column('raw_trust_score', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('relationship_level', sa.String(), nullable=True),
    sa.Column('is_creator', sa.Boolean(), nullable=True),
    sa.Column('demo_key', sa.String(), nullable=True),
    sa.Column('trust_established', sa.Boolean(), nullable=True),
    sa.Column('trust_test_completed', sa.Boolean(), nullable=True),
    sa.Column('trust_test_timestamp', sa.String(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('demo_key', name='uq_chat_meta_demo_key')
    )
    op.create_index(op.f('ix_chat_meta_demo_key'), 'chat_meta', ['demo_key'], unique=False)
    op.create_table('dialogue_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('dialogue_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('message_category', sa.String(), nullable=True),
    sa.Column('focus_points', sa.Text(), nullable=True),
    sa.Column('has_strong_focus', sa.Text(), nullable=True),
    sa.Column('anchor_link', sa.String(), nullable=True),
    sa.Column('has_strong_anchor', sa.Boolean(), nullable=True),
    sa.Column('memories', sa.Text(), nullable=True),
    sa.Column('anchor', sa.String(), nullable=True),
    sa.Column('emoji', sa.String(), nullable=True, comment='Эмодзи, связанное с сообщением (маркер настроения / тега)'),
    sa.Column('vision_context', sa.Text(), nullable=True),
    sa.Column('swiped_message_id', sa.Integer(), nullable=True),
    sa.Column('swiped_message_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_account_created_desc', 'dialogue_history', ['account_id', 'created_at'], unique=False)
    op.create_index('idx_account_id_desc', 'dialogue_history', ['account_id', 'id'], unique=False)
    op.create_index(op.f('ix_dialogue_history_account_id'), 'dialogue_history', ['account_id'], unique=False)
    op.create_table('diary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('entry_text', sa.Text(), nullable=True),
    sa.Column('assistant_answer', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_account_id'), 'diary', ['account_id'], unique=False)
    op.create_table('key_info',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('mood_level', sa.String(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('impressive', sa.Integer(), nullable=True),
    sa.Column('critical', sa.Integer(), nullable=True),
    sa.Column('first_disclosure', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('account_id', 'category', 'subcategory', 'fact')
    )
    op.create_table('model_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('input_tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('input_token_price', sa.Float(), nullable=True),
    sa.Column('output_token_price', sa.Float(), nullable=True),
    sa.Column('account_balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_alarms',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('alarms', sa.JSON(), nullable=False),
    sa.Column('selected_track_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('playlist_moments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage1_text', sa.Text(), nullable=True),
    sa.Column('stage2_text', sa.Text(), nullable=True),
    sa.Column('stage3_text', sa.Text(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['music_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_moments_account_id'), 'playlist_moments', ['account_id'], unique=False)
    op.create_index(op.f('ix_playlist_moments_created_at'), 'playlist_moments', ['created_at'], unique=False)
    op.create_index(op.f('ix_playlist_moments_track_id'), 'playlist_moments', ['track_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repeat_weekly', sa.Boolean(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['chat_meta.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_account_id'), 'reminders', ['account_id'], unique=False)
    op.create_table('track_play_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_played', sa.Float(), nullable=True),
    sa.Column('energy_on_play', postgresql.ENUM('LIGHT_RHYTHMIC', 'WARM_HEARTED', 'CALM_GROUNDING', 'REFLECTIVE_OBSERVING', 'COMPLEX_REFLECTIVE', name='energy_on_play_enum'), nullable=True),
    sa.Column('temperature_on_play', postgresql.ENUM('WARM', 'MODERATE', 'HOT', 'COLD', 'ICY', name='temperature_on_play_enum'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['chat_meta.account_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['music_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_user_descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('energy_description', postgresql.ENUM('LIGHT_RHYTHMIC', 'WARM_HEARTED', 'CALM_GROUNDING', 'REFLECTIVE_OBSERVING', 'COMPLEX_REFLECTIVE', name='energydescription'), nullable=True),
    sa.Column('temperature_description', postgresql.ENUM('WARM', 'MODERATE', 'HOT', 'COLD', 'ICY', name='temperaturedescription'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['chat_meta.account_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['music_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_user_descriptions')
    op.drop_table('track_play_history')
    op.drop_index(op.f('ix_reminders_account_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_playlist_moments_track_id'), table_name='playlist_moments')
    op.drop_index(op.f('ix_playlist_moments_created_at'), table_name='playlist_moments')
    op.drop_index(op.f('ix_playlist_moments_account_id'), table_name='playlist_moments')
    op.drop_table('playlist_moments')
    op.drop_table('user_alarms')
    op.drop_table('music_tracks')
    op.drop_table('model_usage')
    op.drop_table('key_info')
    op.drop_index(op.f('ix_diary_account_id'), table_name='diary')
    op.drop_table('diary')
    op.drop_index(op.f('ix_dialogue_history_account_id'), table_name='dialogue_history')
    op.drop_index('idx_account_id_desc', table_name='dialogue_history')
    op.drop_index('idx_account_created_desc', table_name='dialogue_history')
    op.drop_table('dialogue_history')
    op.drop_index(op.f('ix_chat_meta_demo_key'), table_name='chat_meta')
    op.drop_table('chat_meta')
    # ### end Alembic commands ###
