"""Create TrackPlayHistorybtable

Revision ID: 2f495d480ffe
Revises: 7c745f693f0f
Create Date: 2025-11-08 00:23:59.745543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f495d480ffe'
down_revision: Union[str, Sequence[str], None] = '7c745f693f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_play_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_played', sa.Float(), nullable=True),
    sa.Column('energy_on_play', postgresql.ENUM('LIGHT_RHYTHMIC', 'WARM_HEARTED', 'CALM_GROUNDING', 'REFLECTIVE_OBSERVING', 'COMPLEX_REFLECTIVE', name='energy_on_play_enum'), nullable=True),
    sa.Column('temperature_on_play', postgresql.ENUM('WARM', 'MODERATE', 'HOT', 'COLD', 'ICY', name='temperature_on_play_enum'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['chat_meta.account_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['music_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_table('track_play_history')
    # ### end Alembic commands ###
