"""Add account_id fields and change poi_id to string

Revision ID: 430739aac64e
Revises: c2a1f9c0e2ab
Create Date: 2025-11-07 16:14:02.835465

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '430739aac64e'
down_revision: Union[str, Sequence[str], None] = 'c2a1f9c0e2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # СНАЧАЛА удаляем зависимые таблицы
    op.drop_table('step_points')
    op.drop_table('poi_visits')
    op.drop_table('journal_entries')

    # ПОТОМ удаляем основную таблицу
    op.drop_table('walk_sessions')
    op.drop_table('achievements')
    op.drop_table('streaks')

    # PostGIS таблицы
    op.drop_index(op.f('idx_osm_elements_geometry'), table_name='osm_elements', postgresql_using='gist')
    op.drop_index(op.f('idx_osm_elements_type'), table_name='osm_elements')
    op.drop_table('osm_elements')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_visits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poi_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('poi_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('distance_from_start', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('found_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('emotion_emoji', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emotion_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emotion_color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['walk_sessions.id'], name=op.f('poi_visits_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('poi_visits_pkey'))
    )
    op.create_table('step_points',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['walk_sessions.id'], name=op.f('step_points_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('step_points_pkey'))
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('photo_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poi_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poi_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['walk_sessions.id'], name=op.f('journal_entries_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_entries_pkey'))
    )
    op.create_table('streaks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_active_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('current_length', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('longest_streak', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('streaks_pkey'))
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('osm_elements',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('osm_elements_pkey'))
    )
    op.create_index(op.f('idx_osm_elements_type'), 'osm_elements', ['type'], unique=False)
    op.create_index(op.f('idx_osm_elements_geometry'), 'osm_elements', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('achievements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('achievements_pkey'))
    )
    op.create_table('walk_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('distance_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('walk_sessions_pkey'))
    )
    # ### end Alembic commands ###
