"""init tables

Revision ID: 4cec34486d12
Revises: a6d8a1d13c37
Create Date: 2025-08-31 01:50:48.452348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cec34486d12'
down_revision: Union[str, Sequence[str], None] = 'a6d8a1d13c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogue_history', sa.Column('memories', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialogue_history', 'memories')
    # ### end Alembic commands ###
