"""init tables

Revision ID: 5f2fec739261
Revises: 
Create Date: 2025-08-30 23:19:21.605587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2fec739261'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_meta',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=True),
    sa.Column('raw_trust_score', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('is_creator', sa.Boolean(), nullable=True),
    sa.Column('trust_established', sa.Boolean(), nullable=True),
    sa.Column('trust_test_completed', sa.Boolean(), nullable=True),
    sa.Column('trust_test_timestamp', sa.String(), nullable=True),
    sa.Column('last_updated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('key_info',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('mood_level', sa.String(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('impressive', sa.Integer(), nullable=True),
    sa.Column('critical', sa.Integer(), nullable=True),
    sa.Column('first_disclosure', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('account_id', 'category', 'subcategory', 'fact')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_info')
    op.drop_table('chat_meta')
    # ### end Alembic commands ###
