"""recreate model_usage

Revision ID: 8739622b4544
Revises: 3dcfd99457e3
Create Date: 2025-09-18 00:17:05.955049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8739622b4544'
down_revision: Union[str, Sequence[str], None] = '3dcfd99457e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('input_tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('input_token_price', sa.Float(), nullable=True),
    sa.Column('output_token_price', sa.Float(), nullable=True),
    sa.Column('account_balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_usage')
    # ### end Alembic commands ###
