"""init tables

Revision ID: a6d8a1d13c37
Revises: 5f2fec739261
Create Date: 2025-08-31 01:46:17.507701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d8a1d13c37'
down_revision: Union[str, Sequence[str], None] = '5f2fec739261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('dialogue_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('message_category', sa.String(), nullable=True),
    sa.Column('focus_points', sa.Text(), nullable=True),
    sa.Column('has_strong_focus', sa.Text(), nullable=True),
    sa.Column('anchor_link', sa.String(), nullable=True),
    sa.Column('has_strong_anchor', sa.Boolean(), nullable=True),
    sa.Column('anchor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_history_account_id'), 'dialogue_history', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogue_history_account_id'), table_name='dialogue_history')
    op.drop_table('dialogue_history')
    # ### end Alembic commands ###
