"""add track_user_descriptions

Revision ID: b0d4e919f5c4
Revises: a7360da41693
Create Date: 2025-10-26 06:59:47.679668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0d4e919f5c4'
down_revision: Union[str, Sequence[str], None] = 'a7360da41693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_user_descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('energy_description', postgresql.ENUM('LIGHT_RHYTHMIC', 'WARM_HEARTED', 'CALM_GROUNDING', 'REFLECTIVE_OBSERVING', 'COMPLEX_REFLECTIVE', name='energydescription'), nullable=True),
    sa.Column('temperature_description', postgresql.ENUM('WARM', 'MODERATE', 'HOT', 'COLD', 'ICY', name='temperaturedescription'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['chat_meta.account_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['music_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_meta', sa.Column('relationship_level', sa.String(), nullable=True))
    op.drop_column('chat_meta', 'relationship')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_meta', sa.Column('relationship', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('chat_meta', 'relationship_level')
    op.drop_table('track_user_descriptions')
    # ### end Alembic commands ###
