"""create diary table

Revision ID: bb60b4e64211
Revises: 4cec34486d12
Create Date: 2025-09-14 20:42:15.531458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb60b4e64211'
down_revision: Union[str, Sequence[str], None] = '4cec34486d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('entry_text', sa.Text(), nullable=True),
    sa.Column('assistant_answer', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_account_id'), 'diary', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diary_account_id'), table_name='diary')
    op.drop_table('diary')
    # ### end Alembic commands ###
