"""обновление модели

Revision ID: eb910d557129
Revises: 8739622b4544
Create Date: 2025-09-19 22:17:19.880176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb910d557129'
down_revision: Union[str, Sequence[str], None] = '8739622b4544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_usage', sa.Column('account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_usage', 'account_id')
    # ### end Alembic commands ###
